/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_droidcrypt_Embedder */

#ifndef _Included_com_droidcrypt_Embedder
#define _Included_com_droidcrypt_Embedder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_droidcrypt_Embedder
 * Method:    embed
 * Signature: (Landroid/graphics/Bitmap;Ljava/lang/String;)V
 */
JNIEXPORT jbyteArray JNICALL Java_com_droidcrypt_Embedder_embed
(JNIEnv * env, jclass  obj, jbyteArray bitmap,  jint jwidth, jint jheight, jstring  msg, jintArray num_bits_embeded);


JNIEXPORT jstring JNICALL Java_com_droidcrypt_Embedder_extract
(JNIEnv * env, jclass  obj, jbyteArray bitmap,  jint jwidth, jint jheight, jintArray num_bits_embeded, jint stc_constr_height);


#ifdef __cplusplus
}
#endif
#endif
