/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_droidcrypt_embedder_NativeLib */

#ifndef _Included_com_droidcrypt_embedder_NativeLib
#define _Included_com_droidcrypt_embedder_NativeLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_droidcrypt_embedder_NativeLib
 * Method:    stc_embed
 * Signature: ([BILjava/util/BitSet;I[DZLjava/util/BitSet;I)F
 */
JNIEXPORT jfloat JNICALL Java_com_droidcrypt_embedder_NativeLib_stc_1embed
  (JNIEnv *, jobject, jbyteArray, jint, jobject, jint, jdoubleArray, jboolean, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
