/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_droidcrypt_embedder_NativeLib */

#ifndef _Included_com_droidcrypt_embedder_NativeLib
#define _Included_com_droidcrypt_embedder_NativeLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_droidcrypt_embedder_NativeLib
 * Method:    calc_distortion
 * Signature: (II[FF)F
 */
JNIEXPORT jfloat JNICALL Java_com_droidcrypt_embedder_NativeLib_calc_1distortion
  (JNIEnv *, jobject, jint, jint, jfloatArray, jfloat);

/*
 * Class:     com_droidcrypt_embedder_NativeLib
 * Method:    calc_entropy
 * Signature: (II[FF)F
 */
JNIEXPORT jfloat JNICALL Java_com_droidcrypt_embedder_NativeLib_calc_1entropy
  (JNIEnv *, jobject, jint, jint, jfloatArray, jfloat);

/*
 * Class:     com_droidcrypt_embedder_NativeLib
 * Method:    calc_m1_embed
 * Signature: (II[FF)F
 */
JNIEXPORT jfloat JNICALL Java_com_droidcrypt_embedder_NativeLib_calc_1m1_1embed
  (JNIEnv *, jobject, jint, jint, jfloatArray, jfloat);

#ifdef __cplusplus
}
#endif
#endif
