/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_droidcrypt_Embedder */

#ifndef _Included_com_droidcrypt_Embedder
#define _Included_com_droidcrypt_Embedder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_droidcrypt_Embedder
 * Method:    embed
 * Signature: (Landroid/graphics/Bitmap;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_droidcrypt_Embedder_embed
  (JNIEnv *, jclass, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
